### ISSUE TITLE
Timeout while streaming Messages leads to error

### ISSUE THREAD

**Issue by shashi20008** [eleith/emailjs#234] opened 2018-11-01 15:24 UTC
Description
--
TypeError in EMailJS module leads to server restart. 

Scenario
--
1. Client configures and connects to SMTP server. 
2. Calls `send` method on the returned server object with a message containing file attachment.
3. EMailJS code starts the SMTP message sequence, and completes till DATA. Finally, we the message streaming starts.
5. The message is streamed asynchronously. Occasionally the underlying TCP connection is closed due to timeout.
6. When the next 'data' chunk arrives, the code tries to write it to already closed socket (and null assigned), which throws TypeError.

Fix
--
Please have a look at #233 for a possible fix. Let me know if a different approach should be followed for fixing this issue.

**Comment by zackschuster** [comment] 2020-07-27 07:26
this should be fixed by 81e78bfb4d44776528ff733c967013affa6fed27

closing as duplicate of #205

**Closed by zackschuster** 2020-07-27 07:26 UTC
