### ISSUE TITLE
multiple callback issues

### ISSUE THREAD

**Issue by sturad** [eleith/emailjs#174] opened 2017-03-02 20:56 UTC
We saw emailjs 1.0.8 send double callbacks on a SMTP timeout situation  on an express app running on node v.6.9.5.  

I built your library locally but your example in test/server.js fails for me. So I was unable to attempt a new test for this.  The failure is in a test that might even be testing the same thing, but I don't think the first legit callback is reached before the configured timeout fires.

Thanks for you work!

```
1) Connect to wrong email server Should not call callback multiple times with wrong server configuration:
<      Error: timeout of 5000ms exceeded
<       at Timeout.<anonymous> (/home/steve/code/third-party/emailjs/node_modules/mocha/lib/runnable.js:140:21)
<       at ontimeout (timers.js:380:14)
<       at tryOnTimeout (timers.js:244:5)
<       at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by sturad** [comment] 2017-03-02 22:18
< Error: Can't set headers after they are sent.
<     at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
<     at ServerResponse.header (/home/steve/crashing_app/node_modules/express/lib/response.js:719:10)
<     at ServerResponse.send (/home/steve/crashing_app/node_modules/express/lib/response.js:164:12)
<     at ServerResponse.json (/home/steve/crashing_app/node_modules/express/lib/response.js:250:15)
<     at ServerResponse.send (/home/steve/crashing_app/node_modules/express/lib/response.js:152:21)
<     at EventEmitter.<anonymous> (/home/steve/crashing_app/util/workflow/index.js:32:9)
<     at emitNone (events.js:86:13)
<     at EventEmitter.emit (events.js:185:7)
<     at Object.error (/home/steve/crashing_app/views/login/forgot/index.js:81:18)
<     at Object.callback (/home/steve/crashing_app/util/sendmail/index.js:86:19)
<     at connect (/home/steve/crashing_app/node_modules/emailjs/smtp/client.js:69:19)
<     at caller (/home/steve/crashing_app/node_modules/emailjs/smtp/smtp.js:48:14)
<     at TLSSocket.response (/home/steve/crashing_app/node_modules/emailjs/smtp/smtp.js:138:9)
<     at TLSSocket.g (events.js:291:16)
<     at emitOne (events.js:101:20)
<     at TLSSocket.emit (events.js:188:7)
<     at writeAfterEnd (_stream_writable.js:195:10)
<     at TLSSocket.Writable.write (_stream_writable.js:244:5)
<     at TLSSocket.Socket.write (net.js:658:40)
<     at Object.send (/home/steve/crashing_app/node_modules/emailjs/smtp/smtp.js:186:17)
<     at Object.command (/home/steve/crashing_app/node_modules/emailjs/smtp/smtp.js:212:10)
<     at Object.rset (/home/steve/crashing_app/node_modules/emailjs/smtp/smtp.js:364:10)

**Comment by sturad** [comment] 2017-03-02 22:21
Only seen in 1.0.8 thus far.   I do not see it emailjs@1.0.7.

**Comment by eleith** [comment] 2017-03-17 02:27
i just tried node 6.10 and all tests are currently passing. 

could you provide example snippet that causes the multiple callback issue?

**Comment by eleith** [comment] 2017-03-17 02:29
just tried 6.9.5 to double check, tests also pass for me. 

not sure why it would fail for you?

**Comment by sturad** [comment] 2017-03-31 18:39
Sorry, my nose hasn't been in this recently, and we were fine to stay an older version of your library.  However, I'm posting code as you asked as this might help flush out an error or anti-pattern that might help other consumers of emailjs

```
'use strict';

exports = module.exports = function(req, res, options) {
 
  var renderText = function(callback) {
    res.render(options.textPath, options.locals, function(err, text) {
      if (err) {
        callback(err, null);
      }
      else {
        options.text = text;
        return callback(null, 'done');
      }
    });
  };

  var renderHtml = function(callback) {
    res.render(options.htmlPath, options.locals, function(err, html) {
      if (err) {
        callback(err, null);
      }
      else {
        options.html = html;
        return callback(null, 'done');
      }
    });
  };

  var renderers = [];
  if (options.textPath) {
    renderers.push(renderText);
  }

  if (options.htmlPath) {
    renderers.push(renderHtml);
  }

  require('async').parallel(
    renderers,
    function(err, results){
      if (err) {
        options.error('Email template render failed. '+ err);
        return;
      }

      var attachments = [];

      if (options.html) {
        attachments.push({ data: options.html, alternative: true });
      }

      if (options.attachments) {
        for (var i = 0 ; i < options.attachments.length ; i++) {
          attachments.push(options.attachments[i]);
        }
      }

      var emailjs = require('emailjs/email');
      var emailer = emailjs.server.connect( req.app.config.smtp.credentials );
      debugger;
      emailer.send({
        from: options.from,
        to: options.to,
        'reply-to': options.replyTo || options.from,
        cc: options.cc,
        bcc: options.bcc,
        subject: options.subject,
        text: options.text,
        attachment: attachments
      }, function(err, message) {
        if (err) {
          options.error( err);
          return;
        }
        else {
          options.success(message);
          return;
        }
      });
    }
  );
};
```
where those success and fail callbacks are like this.  Workflow is extends core node EventEmitter

  workflow.on('sendAccountRequestEmail', function(account) {

    req.app.utility.sendmail(req, res, { 
      /// some options
      },
      success: function(message) {
        workflow.emit('createServiceDeskTicket', account);
      },
      error: function(err) {
          // perhaps this needs to be 
          //   return workflow.emit('createServiceDeskTicket', account);
          workflow.emit('createServiceDeskTicket', account);
      }
    });
  });

**Comment by eleith** [comment] 2017-03-31 23:25
thanks for the snippet.

to clarify, are you saying that when SMTP connection timesout, you are seeing the error function being called twice when you expected only one?

**Comment by sturad** [comment] 2017-04-04 18:01
Yes.  This was a learning during the Amazon S3 major outage last month.

**Comment by eleith** [comment] 2017-05-01 03:38
i've done an audit of the emailjs library, and all the places where an error is caught, the server is then closed immediately and should not emit any more callbacks on that instance. i have not been able to create a snippet where i would see multiple error's being called back from one `send` instance. (i was mostly testing out timedout errors, since that is what i expect to hit when there is an aws outage)

please note, if you call 'email.send' five times. everytime it fails, you will get an error callback.

looking at your snippet, the error function seems to be passed in. if the exports function gets called multiple times, you will get `options.error` to be called for everytime it fails.

if this is not what the application further upstream wants (because after the first error response, it puts information in the http response already and sends out some headers), then you would have to track the error response yourself, and after the first one, suppress further error callbacks on your own.

this is merely a guess, i haven't dug too much into your own application to test my hypothesis, so i could be wrong.

i do have a few suggestions

1) if you plan on sending multiple email on one thread, only called `emailjs.server.connect` once, rather than per email
2) track the `options.error` callback, once it is called once, you can then disable future attempts to push data to the response

**Comment by eleith** [comment] 2017-05-01 03:39
closing for now, until i can reproduce. it certainly is possible, but without it, my current investigation didn't turn up any leads.

**Closed by eleith** 2017-05-01 03:38 UTC
